Repository XiaoMi/ha_xiaomi_home, pull requests merged in 2025-01, with the labels that each got.

#101 Feat：add missing parameter state_class
  custom_components/xiaomi_home/miot/miot_device.py
  custom_components/xiaomi_home/miot/miot_spec.py
  custom_components/xiaomi_home/miot/specs/specv2entity.py
  custom_components/xiaomi_home/sensor.py
Labels: enhancement

#535 feat: limit *light.mode count (value-range)
  custom_components/xiaomi_home/light.py
Labels: bug

#561 doc: make git update guide more accurate
  README.md
  doc/README_zh.md
Labels: documentation

#464 fix: fan speed
  README.md
  custom_components/xiaomi_home/fan.py
Labels: bug

#564 feat: filter miwifi.* devices
  custom_components/xiaomi_home/miot/miot_cloud.py
  custom_components/xiaomi_home/miot/specs/spec_filter.json
Labels: enhancement

#583 fix: the number of profile models updated from 660 to 823
  custom_components/xiaomi_home/miot/lan/profile_models.yaml
Labels: bug

#560 fix: fix multi ha instance login
  custom_components/xiaomi_home/config_flow.py
  custom_components/xiaomi_home/miot/miot_client.py
  custom_components/xiaomi_home/miot/miot_cloud.py
  custom_components/xiaomi_home/translations/de.json
  custom_components/xiaomi_home/translations/en.json
  custom_components/xiaomi_home/translations/es.json
  custom_components/xiaomi_home/translations/fr.json
  custom_components/xiaomi_home/translations/ja.json
  custom_components/xiaomi_home/translations/nl.json
  custom_components/xiaomi_home/translations/pt-BR.json
  custom_components/xiaomi_home/translations/pt.json
  custom_components/xiaomi_home/translations/ru.json
  custom_components/xiaomi_home/translations/zh-Hans.json
  custom_components/xiaomi_home/translations/zh-Hant.json
Labels: bug

#365 refactor: refactor miot mips & fix type errors
  custom_components/xiaomi_home/miot/miot_client.py
  custom_components/xiaomi_home/miot/miot_ev.py
  custom_components/xiaomi_home/miot/miot_i18n.py
  custom_components/xiaomi_home/miot/miot_lan.py
  custom_components/xiaomi_home/miot/miot_mips.py
  test/conftest.py
  test/test_ev.py
Labels: enhancement

#636 style: using logging for test case log print
  test/check_rule_format.py
  test/conftest.py
  test/test_cloud.py
  test/test_common.py
  test/test_lan.py
  test/test_mdns.py
  test/test_network.py
  test/test_spec.py
  test/test_storage.py
Labels: enhancement

#638 test: add test case for user cert
  test/conftest.py
  test/test_cloud.py
Labels: enhancement

#622 feat: support remove device
  custom_components/xiaomi_home/__init__.py
  custom_components/xiaomi_home/miot/miot_client.py
Labels: enhancement

#571 feat: add power properties trans
  custom_components/xiaomi_home/miot/specs/specv2entity.py
Labels: enhancement

#627 feat: move web page to html
  custom_components/xiaomi_home/config_flow.py
  custom_components/xiaomi_home/miot/i18n/de.json
  custom_components/xiaomi_home/miot/i18n/en.json
  custom_components/xiaomi_home/miot/i18n/es.json
  custom_components/xiaomi_home/miot/i18n/fr.json
  custom_components/xiaomi_home/miot/i18n/ja.json
  custom_components/xiaomi_home/miot/i18n/nl.json
  custom_components/xiaomi_home/miot/i18n/pt-BR.json
  custom_components/xiaomi_home/miot/i18n/pt.json
  custom_components/xiaomi_home/miot/i18n/ru.json
  custom_components/xiaomi_home/miot/i18n/zh-Hans.json
  custom_components/xiaomi_home/miot/i18n/zh-Hant.json
  custom_components/xiaomi_home/miot/miot_error.py
  custom_components/xiaomi_home/miot/resource/oauth_redirect_page.html
  custom_components/xiaomi_home/miot/web_pages.py
Labels: enhancement

#595 fix: potential problems for properties identification error for sensors
  custom_components/xiaomi_home/miot/specs/specv2entity.py
Labels: enhancement
